### ISSUE TITLE
Websocketの通信が上手くいってない

### ISSUE THREAD

**Issue by RAINeko256** [RAINeko256/shugiou#18]
mqtt.js:4441 WebSocket connection to 'wss://driver.cloudmqtt.com/' failed: 
m @ mqtt.js:4441
g @ mqtt.js:4467
i @ mqtt.js:5068
x._setupStream @ mqtt.js:2844
x._reconnect @ mqtt.js:3484
(anonymous) @ mqtt.js:3504

となる問題を解決したい

**Comment by fuu38** [comment]
恐らくユーザー名/パスワード/WSポートの環境変数が正しく読み込まれてないことが原因だと見てます。Reactのコード内で環境変数吐かせてみて検証しよう。
どーしても解決できなかったらハードコーディングしてみる

**Comment by fuu38** [comment]
とりあえずやること
いまんとこローカルでのテストのときはいちいちハードコーディングしてたので、
dotenv(CRAしたら入ってるっぽい)なりnpmstartの引数なり使って渡してみる、俺らの環境変数読み込むコードに問題があるのか、vercelの設定の問題かを切り分けたい

**Comment by fuu38** [comment]
冷静に考えたらいちいちハードコーディングするの百害あって一利なしって感じだな

**Comment by fuu38** [comment]
REACT_APP_のプレフィクスをつけるのは、CRAして作ったReactアプリケーション内でかんたんに呼べるよってだけっぽいな

**Comment by fuu38** [comment]
dotenv使って試してみた結果、~~環境変数は読み込めているのに接続できない現象が発生した。どうもコード側の問題らしい~~
値間違えてた。接続できた。この結果だけを見るとVercelの設定に問題があるかなーという感じがする
@RAINeko256 もう一度キーと値を確認してほしい！したらDiscordで結果も教えて！

**Comment by RAINeko256** [comment]
環境変数の問題だった、ローカルでは解消したのでデプロイしたあとで要検証！

**Comment by RAINeko256** [comment]
上手くいった！
vercelの環境変数にREACT_APP_ prefixをつける、コードの中の環境変数も同じようにprefixをつけるとうまくいった
